[{"name":{"common":"South Georgia",
"official":"South Georgia and the South Sandwich Islands",
"nativeName":{"eng":{"official":"South Georgia and the South Sandwich Islands",
"common":"South Georgia"}}},
"tld":[".gs"],"cca2":"GS",
"ccn3":"239",
"cca3":"SGS",
"independent":false,
"status":"officially-assigned",
"unMember":false,
"currencies":{"SHP":{"name":"Saint Helena pound",
"symbol":"£"}},
"idd":{"root":"+5",
"suffixes":["00"]},
"capital":["King Edward Point"],
"altSpellings":["GS",
"South Georgia and the South Sandwichi "]}]